Vulkan: batch texture uploads
FNA-XNA/FNA3D pull request #107
Opened 2021-02-03 20:29 UTC by thatcosmonaut

By packing as many textures as we can into the staging buffer before flushing we can greatly reduce the number of sync points on texture upload.

2021-02-04 00:35 UTC, thatcosmonaut commented
Going to tweak this to allocate staging buffers to the device-local/host-visible heap, should improve texture upload speed.

2021-02-04 22:31 UTC, flibitijibibo requested changes
Minor style things. As long as SOR4 tolerates this it's probably fine...

2021-02-04 22:31 UTC, flibitijibibo commented on src/FNA3D_Driver_Vulkan.c
> +
```suggestion
	requiredMemoryPropertyFlags =
		VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT |
		VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
	if (isDeviceLocal)
	{
		requiredMemoryPropertyFlags |=
			VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
	}
	ignoredMemoryPropertyFlags = 0;
```

2021-02-04 22:31 UTC, flibitijibibo commented on src/FNA3D_Driver_Vulkan.c
> +	) {
```suggestion
	if (	dataLength <= MAX_FAST_TEXTURE_STAGING_SIZE &&
		renderer->textureStagingBuffer->fastBuffer != NULL &&
		renderer->textureStagingBuffer->fastBufferOffset + dataLength > renderer->textureStagingBuffer->fastBuffer->size	)
	{
```

2021-02-05 17:36 UTC, flibitijibibo commented on src/FNA3D_Driver_Vulkan.c
> +#define MAX_FAST_TEXTURE_STAGING_SIZE 128000000 /* 128MB */
Similar to what we ran into with the last iteration, 128MB is too large and SOR4 takes a dive when Skytrain is loaded.

```suggestion
#define MAX_FAST_TEXTURE_STAGING_SIZE 64000000 /* 64MB */
```

2021-02-05 18:41 UTC, flibitijibibo requested changes
Just one tab. Will try and split this patch up next.

2021-02-05 18:41 UTC, flibitijibibo commented on src/FNA3D_Driver_Vulkan.c
> +	if (	renderer->textureStagingBuffer->fastBuffer != NULL	&&
```suggestion
	if (	renderer->textureStagingBuffer->fastBuffer != NULL &&
```

2021-02-05 19:06 UTC, flibitijibibo commented
Manually merged via this commit...

https://github.com/FNA-XNA/FNA3D/commit/00cdcfdc67ca5ce35a753b3aad4a5ab8afb31a02

... with the functions moved around in a commit right after:

https://github.com/FNA-XNA/FNA3D/commit/4f6809c842bc5a79d45a0b0fd30c537c1ad9e01a

2021-02-05 19:06 UTC, closed without merging