Vulkan: limit device local memory usage to 80% of capacity
FNA-XNA/FNA3D pull request #108
Opened 2021-02-05 20:08 UTC by thatcosmonaut

2021-02-05 20:39 UTC, flibitijibibo requested changes

2021-02-05 20:39 UTC, flibitijibibo commented on src/FNA3D_Driver_Vulkan.c
> +	if (isDeviceLocal && renderer->deviceLocalHeapUsage + allocationSize > renderer->maxDeviceLocalHeapUsage)
```suggestion
	if (	isDeviceLocal &&
		(renderer->deviceLocalHeapUsage + allocationSize > renderer->maxDeviceLocalHeapUsage)	)
```

2021-02-05 20:39 UTC, flibitijibibo commented on .gitignore
> +*.xcworkspace/
Loose gitignore stuff...

2021-02-09 15:55 UTC, flibitijibibo approved these changes

2021-02-09 15:56 UTC, flibitijibibo commented
Marking as a draft - the patch is perfectly fine as-is, but until we get defrag support we'll have to be a bit greedy with device-local memory.

2021-04-09 03:35 UTC, thatcosmonaut commented
Superseded by https://github.com/FNA-XNA/FNA3D/pull/110

2021-04-09 03:35 UTC, closed without merging